<?php
/**
 * Created by PhpStorm.
 * User: tcameron
 * Date: 7/26/2016
 * Time: 14:00
 */
?>
    <option value="" selected="selected">Select Sector</option>
    <option value="11110 - Education policy and administrative management">11110 - Education policy and administrative management</option>
    <option value="11110 - Education policy and administrative management">11110 - Education policy and administrative management</option>
    <option value="11120 - Education facilities and training">11120 - Education facilities and training</option>
    <option value="11130 - Teacher training">11130 - Teacher training</option>
    <option value="11182 - Educational research">11182 - Educational research</option>
    <option value="11220 - Primary education">11220 - Primary education</option>
    <option value="11230 - Basic life skills for youth and adults ">11230 - Basic life skills for youth and adults </option>
    <option value="11240 - Early childhood education">11240 - Early childhood education</option>
    <option value="11320 - Secondary education">11320 - Secondary education</option>
    <option value="11330 - Vocational training">11330 - Vocational training</option>
    <option value="11420 - Higher education">11420 - Higher education</option>
    <option value="11430 - Advanced technical and managerial training">11430 - Advanced technical and managerial training</option>
    <option value="12110 - Health policy and administrative management">12110 - Health policy and administrative management</option>
    <option value="12181 - Medical education/training">12181 - Medical education/training</option>
    <option value="12182 - Medical research">12182 - Medical research</option>
    <option value="12191 - Medical services">12191 - Medical services</option>
    <option value="12220 - Basic health care">12220 - Basic health care</option>
    <option value="12230 - Basic health infrastructure">12230 - Basic health infrastructure</option>
    <option value="12240 - Basic nutrition">12240 - Basic nutrition</option>
    <option value="12250 - Infectious disease control">12250 - Infectious disease control</option>
    <option value="12261 - Health education">12261 - Health education</option>
    <option value="12262 - Malaria control">12262 - Malaria control</option>
    <option value="12263 - Tuberculosis control">12263 - Tuberculosis control</option>
    <option value="12281 - Health personnel development">12281 - Health personnel development</option>
    <option value="13010 - Population policy and administrative management">13010 - Population policy and administrative management</option>
    <option value="13020 - Reproductive health care">13020 - Reproductive health care</option>
    <option value="13030 - Family planning">13030 - Family planning</option>
    <option value="13040 - STD control including HIV/AIDS">13040 - STD control including HIV/AIDS</option>
    <option value="13081 - Personnel development for population and reproductive health">13081 - Personnel development for population and reproductive health</option>
    <option value="14010 - Water sector policy and administrative management">14010 - Water sector policy and administrative management</option>
    <option value="14015 - Water resources conservation (including data collection)">14015 - Water resources conservation (including data collection)</option>
    <option value="14020 - Water supply and sanitation - large systems">14020 - Water supply and sanitation - large systems</option>
    <option value="14021 - Water supply - large systems ">14021 - Water supply - large systems </option>
    <option value="14022 - Sanitation - large systems">14022 - Sanitation - large systems</option>
    <option value="14030 - Basic drinking water supply and basic sanitation">14030 - Basic drinking water supply and basic sanitation</option>
    <option value="14031 - Basic drinking water supply">14031 - Basic drinking water supply</option>
    <option value="14032 - Basic sanitation">14032 - Basic sanitation</option>
    <option value="14040 - River basins’ development">14040 - River basins’ development</option>
    <option value="14050 - Waste management / disposal">14050 - Waste management / disposal</option>
    <option value="14081 - Education and training in water supply and sanitation">14081 - Education and training in water supply and sanitation</option>
    <option value="15110 - Public sector policy and administrative management">15110 - Public sector policy and administrative management</option>
    <option value="15111 - Public finance management">15111 - Public finance management</option>
    <option value="15114 - Tax policy and tax administration support">15114 - Tax policy and tax administration support</option>
    <option value="15112 - Decentralisation and support to subnational government">15112 - Decentralisation and support to subnational government</option>
    <option value="15113 - Anti-corruption organisations and institutions ">15113 - Anti-corruption organisations and institutions </option>
    <option value="15130 - Legal and judicial development">15130 - Legal and judicial development</option>
    <option value="15150 - Democratic participation and civil society">15150 - Democratic participation and civil society</option>
    <option value="15151 - Elections">15151 - Elections</option>
    <option value="15152 - Legislatures and political parties">15152 - Legislatures and political parties</option>
    <option value="15153 - Media and free flow of information">15153 - Media and free flow of information</option>
    <option value="15160 - Human rights">15160 - Human rights</option>
    <option value="15170 - Women’s equality organisations and institutions">15170 - Women’s equality organisations and institutions</option>
    <option value="15180 - Ending violence against women and girls">15180 - Ending violence against women and girls</option>
    <option value="15210 - Security system management and reform">15210 - Security system management and reform</option>
    <option value="15220 - Civilian peace-building, conflict prevention and resolution">15220 - Civilian peace-building, conflict prevention and resolution</option>
    <option value="15230 - Participation in international peacekeeping operations">15230 - Participation in international peacekeeping operations</option>
    <option value="15240 - Reintegration and SALW control">15240 - Reintegration and SALW control</option>
    <option value="15250 - Removal of land mines and explosive remnants of war">15250 - Removal of land mines and explosive remnants of war</option>
    <option value="15261 - Child soldiers (Prevention and demobilisation) ">15261 - Child soldiers (Prevention and demobilisation) </option>
    <option value="16010 - Social/ welfare services">16010 - Social/ welfare services</option>
    <option value="16020 - Employment policy and administrative management">16020 - Employment policy and administrative management</option>
    <option value="16030 - Housing policy and administrative management">16030 - Housing policy and administrative management</option>
    <option value="16040 - Low-cost housing">16040 - Low-cost housing</option>
    <option value="16050 - Multisector aid for basic social services ">16050 - Multisector aid for basic social services </option>
    <option value="16061 - Culture and recreation">16061 - Culture and recreation</option>
    <option value="16062 - Statistical capacity building">16062 - Statistical capacity building</option>
    <option value="16063 - Narcotics control">16063 - Narcotics control</option>
    <option value="16064 - Social mitigation of HIV/AIDS">16064 - Social mitigation of HIV/AIDS</option>
    <option value="21010 - Transport policy and administrative management">21010 - Transport policy and administrative management</option>
    <option value="21020 - Road transport">21020 - Road transport</option>
    <option value="21030 - Rail transport">21030 - Rail transport</option>
    <option value="21040 - Water transport">21040 - Water transport</option>
    <option value="21050 - Air transport">21050 - Air transport</option>
    <option value="21061 - Storage">21061 - Storage</option>
    <option value="21081 - Education and training in transport and storage">21081 - Education and training in transport and storage</option>
    <option value="22010 - Communications policy and administrative management">22010 - Communications policy and administrative management</option>
    <option value="22020 - Telecommunications">22020 - Telecommunications</option>
    <option value="22030 - Radio/television/print media">22030 - Radio/television/print media</option>
    <option value="22040 - Information and communication technology (ICT)">22040 - Information and communication technology (ICT)</option>
    <option value="23110 - Energy policy and administrative management">23110 - Energy policy and administrative management</option>
    <option value="23181 - Energy education/training">23181 - Energy education/training</option>
    <option value="23182 - Energy research">23182 - Energy research</option>
    <option value="23183 - Energy conservation and demand-side efficiency">23183 - Energy conservation and demand-side efficiency</option>
    <option value="23210 - Energy generation, renewable sources - multiple technologies">23210 - Energy generation, renewable sources - multiple technologies</option>
    <option value="23220 - Hydro-electric power plants">23220 - Hydro-electric power plants</option>
    <option value="23230 - Solar energy">23230 - Solar energy</option>
    <option value="23240 - Wind energy">23240 - Wind energy</option>
    <option value="23250 - Marine energy">23250 - Marine energy</option>
    <option value="23260 - Geothermal energy">23260 - Geothermal energy</option>
    <option value="23270 - Biofuel-fired power plants">23270 - Biofuel-fired power plants</option>
    <option value="23310 - Energy generation, non-renewable sources - unspecified">23310 - Energy generation, non-renewable sources - unspecified</option>
    <option value="23320 - Coal-fired electric power plants">23320 - Coal-fired electric power plants</option>
    <option value="23330 - Oil-fired electric power plants">23330 - Oil-fired electric power plants</option>
    <option value="23340 - Natural gas-fired electric power plants">23340 - Natural gas-fired electric power plants</option>
    <option value="23350 - Fossil fuel electric power plants with carbon capture and storage (CCS)">23350 - Fossil fuel electric power plants with carbon capture and storage (CCS)</option>
    <option value="23360 - Non-renewable waste-fired electric power plants">23360 - Non-renewable waste-fired electric power plants</option>
    <option value="23410 - Hybrid energy electric power plants">23410 - Hybrid energy electric power plants</option>
    <option value="23510 - Nuclear energy electric power plants">23510 - Nuclear energy electric power plants</option>
    <option value="23610 - Heat plants">23610 - Heat plants</option>
    <option value="23620 - District heating and cooling">23620 - District heating and cooling</option>
    <option value="23630 - Electric power transmission and  distribution">23630 - Electric power transmission and  distribution</option>
    <option value="23640 - Gas distribution">23640 - Gas distribution</option>
    <option value="24010 - Financial policy and administrative management">24010 - Financial policy and administrative management</option>
    <option value="24020 - Monetary institutions">24020 - Monetary institutions</option>
    <option value="24030 - Formal sector financial intermediaries">24030 - Formal sector financial intermediaries</option>
    <option value="24040 - Informal/semi-formal financial intermediaries">24040 - Informal/semi-formal financial intermediaries</option>
    <option value="24081 - Education/training in banking and financial services">24081 - Education/training in banking and financial services</option>
    <option value="25010 - Business support services and institutions">25010 - Business support services and institutions</option>
    <option value="25020 - Privatisation">25020 - Privatisation</option>
    <option value="31110 - Agricultural policy and administrative management">31110 - Agricultural policy and administrative management</option>
    <option value="31120 - Agricultural development">31120 - Agricultural development</option>
    <option value="31130 - Agricultural land resources">31130 - Agricultural land resources</option>
    <option value="31140 - Agricultural water resources">31140 - Agricultural water resources</option>
    <option value="31150 - Agricultural inputs">31150 - Agricultural inputs</option>
    <option value="31161 - Food crop production">31161 - Food crop production</option>
    <option value="31162 - Industrial crops/export crops">31162 - Industrial crops/export crops</option>
    <option value="31163 - Livestock">31163 - Livestock</option>
    <option value="31164 - Agrarian reform">31164 - Agrarian reform</option>
    <option value="31165 - Agricultural alternative development">31165 - Agricultural alternative development</option>
    <option value="31166 - Agricultural extension">31166 - Agricultural extension</option>
    <option value="31181 - Agricultural education/training">31181 - Agricultural education/training</option>
    <option value="31182 - Agricultural research">31182 - Agricultural research</option>
    <option value="31191 - Agricultural services">31191 - Agricultural services</option>
    <option value="31192 - Plant and post-harvest protection and pest control">31192 - Plant and post-harvest protection and pest control</option>
    <option value="31193 - Agricultural financial services">31193 - Agricultural financial services</option>
    <option value="31194 - Agricultural co-operatives">31194 - Agricultural co-operatives</option>
    <option value="31195 - Livestock/veterinary services">31195 - Livestock/veterinary services</option>
    <option value="31210 - Forestry policy and administrative management">31210 - Forestry policy and administrative management</option>
    <option value="31220 - Forestry development">31220 - Forestry development</option>
    <option value="31261 - Fuelwood/charcoal">31261 - Fuelwood/charcoal</option>
    <option value="31281 - Forestry education/training">31281 - Forestry education/training</option>
    <option value="31282 - Forestry research">31282 - Forestry research</option>
    <option value="31291 - Forestry services">31291 - Forestry services</option>
    <option value="31310 - Fishing policy and administrative management">31310 - Fishing policy and administrative management</option>
    <option value="31320 - Fishery development">31320 - Fishery development</option>
    <option value="31381 - Fishery education/training">31381 - Fishery education/training</option>
    <option value="31382 - Fishery research">31382 - Fishery research</option>
    <option value="31391 - Fishery services">31391 - Fishery services</option>
    <option value="32110 - Industrial policy and administrative management">32110 - Industrial policy and administrative management</option>
    <option value="32120 - Industrial development">32120 - Industrial development</option>
    <option value="32130 - Small and medium-sized enterprises (SME) development">32130 - Small and medium-sized enterprises (SME) development</option>
    <option value="32140 - Cottage industries and handicraft">32140 - Cottage industries and handicraft</option>
    <option value="32161 - Agro-industries">32161 - Agro-industries</option>
    <option value="32162 - Forest industries">32162 - Forest industries</option>
    <option value="32163 - Textiles, leather and substitutes">32163 - Textiles, leather and substitutes</option>
    <option value="32164 - Chemicals ">32164 - Chemicals </option>
    <option value="32165 - Fertilizer plants">32165 - Fertilizer plants</option>
    <option value="32166 - Cement/lime/plaster">32166 - Cement/lime/plaster</option>
    <option value="32167 - Energy manufacturing">32167 - Energy manufacturing</option>
    <option value="32168 - Pharmaceutical production">32168 - Pharmaceutical production</option>
    <option value="32169 - Basic metal industries">32169 - Basic metal industries</option>
    <option value="32170 - Non-ferrous metal industries">32170 - Non-ferrous metal industries</option>
    <option value="32171 - Engineering">32171 - Engineering</option>
    <option value="32172 - Transport equipment industry">32172 - Transport equipment industry</option>
    <option value="32182 - Technological research and development">32182 - Technological research and development</option>
    <option value="32210 - Mineral/mining policy and administrative management">32210 - Mineral/mining policy and administrative management</option>
    <option value="32220 - Mineral prospection and exploration">32220 - Mineral prospection and exploration</option>
    <option value="32261 - Coal">32261 - Coal</option>
    <option value="32262 - Oil and gas">32262 - Oil and gas</option>
    <option value="32263 - Ferrous metals">32263 - Ferrous metals</option>
    <option value="32264 - Nonferrous metals">32264 - Nonferrous metals</option>
    <option value="32265 - Precious metals/materials">32265 - Precious metals/materials</option>
    <option value="32266 - Industrial minerals">32266 - Industrial minerals</option>
    <option value="32267 - Fertilizer minerals">32267 - Fertilizer minerals</option>
    <option value="32268 - Offshore minerals">32268 - Offshore minerals</option>
    <option value="32310 - Construction policy and administrative management">32310 - Construction policy and administrative management</option>
    <option value="33110 - Trade policy and administrative management">33110 - Trade policy and administrative management</option>
    <option value="33120 - Trade facilitation">33120 - Trade facilitation</option>
    <option value="33130 - Regional trade agreements (RTAs)">33130 - Regional trade agreements (RTAs)</option>
    <option value="33140 - Multilateral trade negotiations">33140 - Multilateral trade negotiations</option>
    <option value="33150 - Trade-related adjustment">33150 - Trade-related adjustment</option>
    <option value="33181 - Trade education/training">33181 - Trade education/training</option>
    <option value="33210 - Tourism policy and administrative management">33210 - Tourism policy and administrative management</option>
    <option value="41010 - Environmental policy and administrative management">41010 - Environmental policy and administrative management</option>
    <option value="41020 - Biosphere protection">41020 - Biosphere protection</option>
    <option value="41030 - Bio-diversity">41030 - Bio-diversity</option>
    <option value="41040 - Site preservation">41040 - Site preservation</option>
    <option value="41050 - Flood prevention/control">41050 - Flood prevention/control</option>
    <option value="41081 - Environmental education/ training">41081 - Environmental education/ training</option>
    <option value="41082 - Environmental research">41082 - Environmental research</option>
    <option value="43010 - Multisector aid">43010 - Multisector aid</option>
    <option value="43030 - Urban development and management">43030 - Urban development and management</option>
    <option value="43040 - Rural development">43040 - Rural development</option>
    <option value="43050 - Non-agricultural alternative development">43050 - Non-agricultural alternative development</option>
    <option value="43081 - Multisector education/training">43081 - Multisector education/training</option>
    <option value="43082 - Research/scientific institutions">43082 - Research/scientific institutions</option>
    <option value="51010 - General budget support-related aid">51010 - General budget support-related aid</option>
    <option value="52010 - Food aid/Food security programmes">52010 - Food aid/Food security programmes</option>
    <option value="53030 - Import support (capital goods)">53030 - Import support (capital goods)</option>
    <option value="53040 - Import support (commodities)">53040 - Import support (commodities)</option>
    <option value="60010 - Action relating to debt">60010 - Action relating to debt</option>
    <option value="60020 - Debt forgiveness ">60020 - Debt forgiveness </option>
    <option value="60030 - Relief of multilateral debt">60030 - Relief of multilateral debt</option>
    <option value="60040 - Rescheduling and refinancing">60040 - Rescheduling and refinancing</option>
    <option value="60061 - Debt for development swap">60061 - Debt for development swap</option>
    <option value="60062 - Other debt swap">60062 - Other debt swap</option>
    <option value="60063 - Debt buy-back">60063 - Debt buy-back</option>
    <option value="72010 - Material relief assistance and services ">72010 - Material relief assistance and services </option>
    <option value="72040 - Emergency food aid">72040 - Emergency food aid</option>
    <option value="72050 - Relief co-ordination; protection and support services ">72050 - Relief co-ordination; protection and support services </option>
    <option value="73010 - Reconstruction relief and rehabilitation">73010 - Reconstruction relief and rehabilitation</option>
    <option value="74010 - Disaster prevention and preparedness">74010 - Disaster prevention and preparedness</option>
    <option value="91010 - Administrative costs (non-sector allocable)">91010 - Administrative costs (non-sector allocable)</option>
    <option value="93010 - Refugees in donor countries (non-sector allocable)">93010 - Refugees in donor countries (non-sector allocable)</option>
    <option value="99810 - Sectors not specified">99810 - Sectors not specified</option>
    <option value="99820 - Promotion of development awareness (non-sector allocable)">99820 - Promotion of development awareness (non-sector allocable)</option>
    <option value="81000 - Foreign Direct Investment">81000 - Foreign Direct Investment</option>
    <option value="82000 - Porfolio Investment">82000 - Porfolio Investment</option>
    <option value="82010 - Bonds">82010 - Bonds</option>
    <option value="82020 - Stocks">82020 - Stocks</option>
    <option value="83010 - Export Credits, Non Guarantee">83010 - Export Credits, Non Guarantee</option>
    <option value="83020 - Export Credits, Guaranteed">83020 - Export Credits, Guaranteed</option>
    <option value="84000 - Bank Lending, Long Term">84000 - Bank Lending, Long Term</option>
    <option value="85000 - Grants by NGOs">85000 - Grants by NGOs</option>
    <option value="87000 - Personal Remittances">87000 - Personal Remittances</option>
    <option value="99910 - Multilateral Records">99910 - Multilateral Records</option>

